espnet: 0.9.8
files:
  asr_model_file: exp/asr_train_asr_conformer6_n_fft512_hop_length256_raw_en_bpe5000_scheduler_confwarmup_steps40000_optim_conflr0.0025_sp/valid.acc.ave_10best.pth
  lm_file: exp/lm_train_lm_transformer2_bpe5000_scheduler_confwarmup_steps25000_batch_bins500000000_accum_grad2_use_amptrue/valid.loss.ave_10best.pth
python: "3.8.8 (default, Feb 24 2021, 21:46:12) \n[GCC 7.3.0]"
timestamp: 1615779810.871871
torch: 1.8.0
yaml_files:
  asr_train_config: exp/asr_train_asr_conformer6_n_fft512_hop_length256_raw_en_bpe5000_scheduler_confwarmup_steps40000_optim_conflr0.0025_sp/config.yaml
  lm_train_config: exp/lm_train_lm_transformer2_bpe5000_scheduler_confwarmup_steps25000_batch_bins500000000_accum_grad2_use_amptrue/config.yaml
