accum-grad: 1
adim: 256
aheads: 8
backend: pytorch
batch-size: 32
maxlen-in: 512
maxlen-out: 150
#batch-bins: 15000000
dlayers: 6
dropout-rate: 0.1
dunits: 2048
elayers: 12
epochs: 50
eunits: 1024
grad-clip: 5
lsm-weight: 0.1
model-module: espnet.nets.pytorch_backend.e2e_asr_cif:E2E
mtlalpha: 0.5
report-cer: true
opt: noam
patience: 0
sortagrad: 0
transformer-attn-dropout-rate: 0.0
transformer-init: pytorch
transformer-input-layer: conv2d
transformer-length-normalized-loss: false
transformer-lr: 10.0
transformer-warmup-steps: 25000

transformer-encoder-activation-type: swish
transformer-encoder-pos-enc-layer-type: rel_pos
transformer-encoder-selfattn-layer-type: rel_selfattn
macaron-style: true
use-cnn-module: true
cnn-module-kernel: 15

cif-quantity-loss-weight: 0.5
cif-nat-decoder: True

