batch_type: numel
batch_bins: 1500000
accum_grad: 1
max_epoch: 100
patience: none
# The initialization method for model parameters
init: xavier_uniform
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10

#freeze_param: [
#    "encoder.encoders.mask_emb", "encoder.encoders.feature_extractor",
#    "encoder.encoders.post_extract_proj", "encoder.encoders.encoder.pos_conv",
#    "encoder.encoders.encoder.layers.0", "encoder.encoders.encoder.layers.1", "encoder.encoders.encoder.layers.2",
#    "encoder.encoders.encoder.layers.3", "encoder.encoders.encoder.layers.4", "encoder.encoders.encoder.layers.5",
#    "encoder.encoders.encoder.layers.6", "encoder.encoders.encoder.layers.7", "encoder.encoders.encoder.layers.8",
#    "encoder.encoders.encoder.layers.9", "encoder.encoders.encoder.layers.10", "encoder.encoders.encoder.layers.11",
#    "encoder.encoders.encoder.layer_norm", "encoder.encoders.layer_norm",
#]

input_size: 2048
encoder: hubert
encoder_conf:
    output_size: 1024
    normalize_before: false
    freeze_finetune_updates: 100000 # 10000
    #hubert_url: espnet
    #hubert_dir_path: exp/asr_train_asr_hubert_base_960h_pretrain_raw_en_word/
    hubert_url: https://dl.fbaipublicfiles.com/hubert/hubert_base_ls960.pt
    hubert_dir_path: ./downloads/hubert_pretrained_models/hubert_base_ls960.pt


model_conf:
    ctc_weight: 1.0
    lsm_weight: 0.1
    length_normalized_loss: false

optim: adam
optim_conf:
    lr: 0.00002
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 4000 # 10000

unused_parameters: true

frontend: null

normalize: null

specaug: null
