batch_type: numel
batch_bins: 3200000
accum_grad: 1
max_epoch: 400
patience: none
# The initialization method for model parameters
init: xavier_uniform
best_model_criterion:
-   - valid
    - loss
    - min
keep_nbest_models: 10

#freeze_param: [
#    "encoder.encoders.mask_emb", "encoder.encoders.feature_extractor",
#    "encoder.encoders.post_extract_proj", "encoder.encoders.encoder.pos_conv",
#    "encoder.encoders.encoder.layers.0", "encoder.encoders.encoder.layers.1", "encoder.encoders.encoder.layers.2",
#    "encoder.encoders.encoder.layers.3", "encoder.encoders.encoder.layers.4", "encoder.encoders.encoder.layers.5",
#    "encoder.encoders.encoder.layers.6", "encoder.encoders.encoder.layers.7", "encoder.encoders.encoder.layers.8",
#    "encoder.encoders.encoder.layers.9", "encoder.encoders.encoder.layers.10", "encoder.encoders.encoder.layers.11",
#    "encoder.encoders.encoder.layer_norm", "encoder.encoders.layer_norm",
#]

freeze_param: [
    "encoder.encoders.mask_emb", "encoder.encoders.feature_extractor",
    "encoder.encoders.post_extract_proj", "encoder.encoders.encoder.pos_conv",
]

input_size: 1
encoder: hubert
encoder_conf:
    output_size: 256
    normalize_before: false
    freeze_finetune_updates: 10000
    #hubert_url: espnet
    #hubert_dir_path: exp/asr_train_asr_hubert_base_960h_pretrain_raw_en_word/
    hubert_url: https://dl.fbaipublicfiles.com/hubert/hubert_base_ls960.pt
    hubert_dir_path: ./downloads/hubert_pretrained_models/hubert_base_ls960.pt


model_conf:
    ctc_weight: 1.0
    lsm_weight: 0.1
    length_normalized_loss: false

optim: adam
optim_conf:
    lr: 0.00002
    
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 1000 # 4000

unused_parameters: true

frontend: null

normalize: null

specaug: null

## asr_train_asr_hubert_base_10h_finetuning_last_1layer_raw_en_char
### WER

#|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
#|---|---|---|---|---|---|---|---|---|
#|decode_asr_asr_model_valid.loss.ave/dev_clean|2703|54402|88.7|10.9|0.4|0.7|12.0|78.5|
#|decode_asr_asr_model_valid.loss.ave/dev_other|2864|50948|83.0|16.0|1.0|1.1|18.1|85.8|
#|decode_asr_asr_model_valid.loss.ave/test_clean|2620|52576|88.4|11.1|0.4|0.8|12.3|78.9|
#|decode_asr_asr_model_valid.loss.ave/test_other|2939|52343|83.0|16.0|1.0|1.3|18.3|86.9|

#### CER

#|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
#|---|---|---|---|---|---|---|---|---|
#|decode_asr_asr_model_valid.loss.ave/dev_clean|2703|288456|97.5|1.4|1.2|0.9|3.4|78.5|
#|decode_asr_asr_model_valid.loss.ave/dev_other|2864|265951|95.4|2.5|2.1|1.5|6.1|85.8|
#|decode_asr_asr_model_valid.loss.ave/test_clean|2620|281530|97.5|1.4|1.1|0.9|3.4|78.9|
#|decode_asr_asr_model_valid.loss.ave/test_other|2939|272758|95.5|2.5|2.1|1.5|6.1|86.9|