config: conf/tuning/train_asr_hubert_base_10h_finetuning_espnet.yaml
print_config: false
log_level: INFO
dry_run: false
iterator_type: sequence
output_dir: asr_stats_raw_en_char_espnet/logdir/stats.4
ngpu: 0
seed: 0
num_workers: 1
num_att_plot: 3
dist_backend: nccl
dist_init_method: env://
dist_world_size: null
dist_rank: null
local_rank: null
dist_master_addr: null
dist_master_port: null
dist_launcher: null
multiprocessing_distributed: false
unused_parameters: true
sharded_ddp: false
cudnn_enabled: true
cudnn_benchmark: false
cudnn_deterministic: true
collect_stats: true
write_collected_feats: false
max_epoch: 200
patience: null
val_scheduler_criterion:
- valid
- loss
early_stopping_criterion:
- valid
- loss
- min
best_model_criterion:
-   - valid
    - loss
    - min
keep_nbest_models: 10
grad_clip: 5.0
grad_clip_type: 2.0
grad_noise: false
accum_grad: 1
no_forward_run: false
resume: false
train_dtype: float32
use_amp: false
log_interval: null
use_tensorboard: true
use_wandb: false
wandb_project: null
wandb_id: null
detect_anomaly: false
pretrain_path: null
init_param: []
ignore_init_mismatch: false
freeze_param:
- encoder.encoders.mask_emb
- encoder.encoders.feature_extractor
- encoder.encoders.post_extract_proj
- encoder.encoders.encoder.pos_conv
num_iters_per_epoch: null
batch_size: 20
valid_batch_size: null
batch_bins: 10000000
valid_batch_bins: null
train_shape_file:
- asr_stats_raw_en_char_espnet/logdir/train.4.scp
valid_shape_file:
- asr_stats_raw_en_char_espnet/logdir/valid.4.scp
batch_type: numel
valid_batch_type: null
fold_length: []
sort_in_batch: descending
sort_batch: descending
multiple_iterator: false
chunk_length: 500
chunk_shift_ratio: 0.5
num_cache_chunks: 1024
train_data_path_and_name_and_type:
-   - dump/raw/train_10h/wav.scp
    - speech
    - sound
-   - dump/raw/train_10h/text
    - text
    - text
valid_data_path_and_name_and_type:
-   - dump/raw/dev/wav.scp
    - speech
    - sound
-   - dump/raw/dev/text
    - text
    - text
allow_variable_data_keys: false
max_cache_size: 0.0
max_cache_fd: 32
valid_max_cache_size: null
optim: adam
optim_conf:
    lr: 2.0e-05
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 1000
token_list:
- <blank>
- <unk>
- <space>
- E
- T
- A
- O
- N
- I
- H
- S
- R
- D
- L
- U
- M
- W
- C
- F
- G
- Y
- P
- B
- V
- K
- ''''
- X
- J
- Q
- Z
- <sos/eos>
init: xavier_uniform
input_size: 1
ctc_conf:
    dropout_rate: 0.0
    ctc_type: builtin
    reduce: true
    ignore_nan_grad: false
model_conf:
    ctc_weight: 1.0
    lsm_weight: 0.1
    length_normalized_loss: false
use_preprocessor: true
token_type: char
bpemodel: null
non_linguistic_symbols: null
cleaner: null
g2p: null
speech_volume_normalize: null
rir_scp: null
rir_apply_prob: 1.0
noise_scp: null
noise_apply_prob: 1.0
noise_db_range: '13_15'
frontend: null
frontend_conf: {}
specaug: null
specaug_conf: {}
normalize: null
normalize_conf: {}
preencoder: null
preencoder_conf: {}
encoder: hubert
encoder_conf:
    output_size: 1024
    normalize_before: false
    freeze_finetune_updates: 1000
    hubert_url: espnet
    hubert_dir_path: exp/asr_train_asr_hubert_base_960h_pretrain_raw_en_word/
decoder: rnn
decoder_conf: {}
required:
- output_dir
- token_list
version: 0.9.10
distributed: false
